spring.application.name=Scripta
spring.datasource.url=jdbc:mysql://localhost:3306/scripta_db
spring.datasource.username=root
spring.datasource.password=*****
jwt.secret=My Name is John and I like to play football
jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.cache.type=redis
spring.data.redis.host=redis-14597.crce263.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=14597
spring.data.redis.password=ecKNCz7yQDEFXD3EzIwLrouTpdYobgx5
spring.data.redis.timeout=2000